---
title: "ME315_Lista07_Elisa"
format: pdf
editor: visual
---

## Lista 7

```{r}
library(DBI)
library(RSQLite)
knitr::opts_chunk$set(max.print = Inf)
# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "purchase.sqlite")
```

```{sql connection=con}
select *
from purchase
```

01\.

```{sql connection=con}
select pno, sum(cost) as custo_total
from purchase
group by pno
```

02\.

```{sql connection=con}
select eno, sum(cost) as custo_total
from purchase
group by eno
```

03\.

```{sql connection=con}
select pjno, eno, sum(cost) as custo_total
from purchase
group by pjno, eno
order by pjno, eno
```

04\.

```{sql connection=con}
select pno, sno, sum(cost) as custo_total
from purchase
group by pno, sno
order by pno, sno
```

05\.

```{sql connection=con}
select pjno, eno, sno, sum(cost) as custo_total
from purchase
group by pjno, eno, sno
order by pjno, eno, sno
```

06\.

```{sql connection=con}
select pno, sno, eno, sum(cost) as custo_total
from purchase
group by pno, sno, eno
order by pno, sno, eno
```

07\.

```{sql connection=con}
select pjno, eno, sno, sum(cost) as custo_total
from purchase
where pjno <> 'pj2'
group by pjno, eno, sno
```

08\.

```{sql connection=con}
select pno, sno, eno, sum(cost) as custo_total
from purchase
group by pno, sno, eno
having sum(cost) >= 2000
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
