---
title: "ME315_Lista06_Elisa"
format: pdf
editor: visual
---

## Lista 6

### Tabela Preserve

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "me315.sqlite")
```

01\.

```{sql connection=con}
select state, min(acres)
from preserve
group by state
```

02\.

```{sql connection=con}
select state, max(acres)
from preserve 
where acres <= 10000
group by state
```

03\.

```{sql connection=con}
select state, max(acres)
from preserve
where acres <= 10000
group by state 
order by max(acres) desc
```

04\.

```{sql connection=con}
select state, max(acres)
from preserve
group by state
having max(acres) < 25000

```

05\.

```{sql connection=con}
select state, min(acres)
from preserve
group by state
having min(acres) < 100
```

06\.

```{sql connection=con}
select state, pname, acres
from preserve
where acres > 1000
group by state 
having max(acres) < 25000
```

07\.

```{sql connection=con}
select state, acres
from preserve
group by state
having sum(acres) >= 10000 and sum(acres) <= 50000
```

08\.

```{sql connection=con}
SELECT MAX(MEDIA)
FROM (SELECT AVG(ACRES) AS MEDIA
      FROM PRESERVE
      GROUP BY STATE) 
```

### Tabela Employee

09\.

```{sql connection=con}
SELECT DNO, AVG(SALARY)
FROM EMPLOYEE
GROUP BY DNO
```

10\.

```{sql connection=con}
SELECT DNO, SUM(SALARY), MAX(SALARY), MIN(SALARY)
FROM EMPLOYEE
GROUP BY DNO
```

11\.

```{sql connection=con}
SELECT DNO, COUNT(*)
FROM EMPLOYEE
WHERE DNO <> 40
GROUP BY DNO
```

12\.

```{sql connection=con}
SELECT DNO, COUNT(*)
FROM EMPLOYEE
GROUP BY DNO
HAVING COUNT(*) > 2
```

13\.

```{sql connection=con}
SELECT STATE, SUM(ACRES) AS "SUM (ACRES)"
FROM PRESERVE
GROUP BY STATE
UNION ALL
SELECT 'Total', SUM(ACRES)
FROM PRESERVE;
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
